/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2023-12-20 14:55:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(" body{\r\n");
      out.write("    background-image: url(https://images.pexels.com/photos/15200485/pexels-photo-15200485.jpeg?cs=srgb&dl=pexels-clayton-de-araujo-15200485.jpg&fm=jpg);\r\n");
      out.write("    background-repeat: no-repeat;\r\n");
      out.write("    background-size: cover;\r\n");
      out.write("    background-attachment:fixed;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#container1{\r\n");
      out.write("    border: 2px solid black;\r\n");
      out.write("    box-shadow: 0px 0px 5px gray;\r\n");
      out.write("    margin-left: 400px;\r\n");
      out.write("    height: 800px;\r\n");
      out.write("    background: rgba(2, 2, 2, 0.3);\r\n");
      out.write("    width: 600px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".form button{\r\n");
      out.write("    width: 230px;\r\n");
      out.write("    margin-bottom: 15px;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    border: 1px solid gainsboro;\r\n");
      out.write("    background-color: rgba(250, 244, 244, 0.7);;\r\n");
      out.write("    margin-left: 170px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form button{\r\n");
      out.write("    width: 253px;\r\n");
      out.write("    margin-bottom: 15px;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("    font-weight: 400;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    border: none;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    background:#166fe5;\r\n");
      out.write("    cursor:pointer;\r\n");
      out.write("    margin-left: 170px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("h1{\r\n");
      out.write("    font-family:'Rubik sMoonrocks', sans-serif;    \r\n");
      out.write("    color: white;     \r\n");
      out.write("    font-weight: lighter; \r\n");
      out.write("    font-size:30px;\r\n");
      out.write("    position:relative;\r\n");
      out.write("    left:220px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p{\r\n");
      out.write("    color: white;\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("    position:relative;\r\n");
      out.write("    left:190px;\r\n");
      out.write("    top:-70px;\r\n");
      out.write("\r\n");
      out.write("}   \r\n");
      out.write("\r\n");
      out.write("hr{\r\n");
      out.write("    width: 270px;\r\n");
      out.write("    margin-left: 158px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("h2{\r\n");
      out.write("    font-family:'Rubiks Moonrocks', sans-serif;    \r\n");
      out.write("    color: white;     \r\n");
      out.write("    font-weight: bold; \r\n");
      out.write("    font-size:15px;\r\n");
      out.write("    position:relative;\r\n");
      out.write("    left:260px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"container1\">\r\n");
      out.write("        <h1>QUALLECT</h1>\r\n");
      out.write("         <br><br><br>\r\n");
      out.write("        <p>Quality Selects at your doorstep!</p>\r\n");
      out.write("        <br>\r\n");
      out.write("        <h2>Welcome</h2>\r\n");
      out.write("        <br>\r\n");
      out.write("        <form class=\"form\"   method=\"post\">\r\n");
      out.write("           <button formaction=\"CustomerLog.jsp\" type=\"submit\">Customer</button>\r\n");
      out.write("           <button formaction=\"RestaurantLog.jsp\" type=\"submit\">Restaurant Owner</button>\r\n");
      out.write("        </form>\r\n");
      out.write("        <hr>\r\n");
      out.write("        <br>\r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
