/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2023-12-25 11:31:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Quallect.dto.OwnerRegister;
import Quallect.dto.FoodItems;
import java.util.List;

public final class mainpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Quallect.dto.OwnerRegister");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("Quallect.dto.FoodItems");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("*{\r\n");
      out.write("margin:0%;\r\n");
      out.write("padding:0%;\r\n");
      out.write("box-sizing:border-box;\r\n");
      out.write("}\r\n");
      out.write("#container {\r\n");
      out.write("margin:0px;\r\n");
      out.write("	border: 2px solid;\r\n");
      out.write("	height: 80px;\r\n");
      out.write("	background-color: rgb(11, 101, 161);\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	position:fixed;\r\n");
      out.write("	width:100%;\r\n");
      out.write("	z-index:1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#container h1 {\r\n");
      out.write("	padding-left: 43%;\r\n");
      out.write("	padding-top:30px;\r\n");
      out.write("	line-height: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#container p {\r\n");
      out.write("	padding-left: 0%;\r\n");
      out.write("	padding-top:10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#logout {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 40px;\r\n");
      out.write("	left: 92%;\r\n");
      out.write("	font-size: 25px;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#container1 {\r\n");
      out.write("margin-top:80px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("	border: 2px solid;\r\n");
      out.write("	line-height: 5px;\r\n");
      out.write("	background-color: rgb(158, 208, 241);\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	position:fixed;\r\n");
      out.write("	width:100%;\r\n");
      out.write("	z-index:1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#container1 h2 {\r\n");
      out.write("	padding-left: 46%;\r\n");
      out.write("	padding-top:20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#add {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 40px;\r\n");
      out.write("	left: 80%;\r\n");
      out.write("	font-size: 25px;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#maindiv {\r\n");
      out.write("	margin-left:120%;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-wrap: wrap;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	justify-content: space-around;\r\n");
      out.write("	height: 160px;\r\n");
      out.write("	width: 400px;\r\n");
      out.write("	border-radius: 15px;\r\n");
      out.write("	background-image: linear-gradient(20deg, purple, rgb(119, 81, 88),\r\n");
      out.write("		rgb(65, 166, 225));\r\n");
      out.write("		border-radius:20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".name {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	padding-top:20px;\r\n");
      out.write("	height: 45px;\r\n");
      out.write("	color: #ff9;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p {\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button {\r\n");
      out.write("	background-color: rgb(158, 208, 241, 0.6);\r\n");
      out.write("	color: #000;\r\n");
      out.write("	border: none;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	border-radius: 20px;\r\n");
      out.write("	width: 70px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	margin-left: 50px;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".price {\r\n");
      out.write("	background-color: rgb(158, 208, 241, 0.6);\r\n");
      out.write("	width: 80px;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	border-radius: 20px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#discription {\r\n");
      out.write("	border: 2px;\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	padding-top:10px;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cardbutton {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-evenly;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("	color: white;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:hover {\r\n");
      out.write("	text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("#restaurant{\r\n");
      out.write("position:absolute;\r\n");
      out.write("top:150px;\r\n");
      out.write("	height:40px;\r\n");
      out.write("	position:fixed;\r\n");
      out.write("	display:flex;\r\n");
      out.write("}\r\n");
      out.write("#restaurant h1{\r\n");
      out.write("	padding-left:2%;\r\n");
      out.write("	color:#0408e679;\r\n");
      out.write("}\r\n");
      out.write("#maindiv1{\r\n");
      out.write("	position:absolute;\r\n");
      out.write("	top:150px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"container\">\r\n");
      out.write("		<h1>QUALLECT</h1>\r\n");
      out.write("		<p>Quality Selects at your doorstep!</p>\r\n");
      out.write("		<a href=\"RestaurantLog.jsp\" id=\"logout\">Logout</a>\r\n");
      out.write("		");

		OwnerRegister db = (OwnerRegister) request.getAttribute("db");
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<a href=\"add?id=");
      out.print(db.getId());
      out.write("\" id=\"add\">AddItems</a>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"container1\">\r\n");
      out.write("		<h2>Welcome</h2>\r\n");
      out.write("		<hr style=\"margin-top:15px;\">\r\n");
      out.write("		<br>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"restaurant\">\r\n");
      out.write("		<h2>Restaurant:</h2><h1>");
      out.print(db.getRestaurantname() );
      out.write("</h1>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div id=\"maindiv1\"> \r\n");
      out.write("	");

	List<FoodItems> result = (List<FoodItems>) request.getAttribute("foodItems");
	
      out.write("\r\n");
      out.write("	<table>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th></th>\r\n");
      out.write("			<th></th>\r\n");
      out.write("			<th></th>\r\n");
      out.write("		</tr>\r\n");
      out.write("		");

		for (FoodItems food : result) {
		
      out.write("\r\n");
      out.write("		<tr>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("			<td>\r\n");
      out.write("				<div id=\"maindiv\">\r\n");
      out.write("					<div class=\"container\">\r\n");
      out.write("						<div class=\"name\">\r\n");
      out.write("							<h3>");
      out.print(food.getDish_name());
      out.write("</h3>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div id=\"discription\">\r\n");
      out.write("							<p>");
      out.print(food.getDescription());
      out.write("</p>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"cardbutton\">\r\n");
      out.write("							<div class=\"price\">\r\n");
      out.write("								Rs.");
      out.print(food.getPrice());
      out.write("</div>\r\n");
      out.write("							<div class=\"button\">\r\n");
      out.write("								<a href=\"update?id=");
      out.print(food.getId());
      out.write("\">Update</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"button\">\r\n");
      out.write("								<a href=\"delete?id=");
      out.print(food.getId());
      out.write("\">Delete</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					</div>\r\n");
      out.write("			</td>\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("		</tr>\r\n");
      out.write("		");

		}
		
      out.write("\r\n");
      out.write("	</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
